### ISSUE TITLE
アプリの起動エラーについてご相談

### ISSUE THREAD

**Issue by blueink-ao** [safx/leptos-taskboard-sample#1]
開発者様

はじめまして。
RUSTに興味があり独学で勉強している者です。RUSTとLeptosで検索をしていたところ、こちらのページにヒットをしまして、デモ使わせていただきました。動作にとても感動しまして、さっそくこちらからクローンさせていただいたのですが、cargo run すると多数のエラーが出て起動することができませんが、エラーの数が多く、初心者の私にはどうすることもできませんでしたが、ぜひ私の環境で動作を見て見たいと思っています。
記事とプログラムを公開されたのが１年ほど前のようで、LeptosやRUST側で変わったなどいろいろあると思うのですが、お手数ではございますが、是非、こちらのコードで勉強をしてみたいので。今の最新のバージョンで動作するように原因を見ていただけると非常に嬉しいです。どうぞよろしくお願いいたします。

**Comment by safx** [comment]
@blueink-ao さん、興味を持っていただいてありがとうございます！

blueink-aoさんがどこで困っておられるのか文面から判断できませんので、
ひとまず一般的な起動手段のみを書いておきます。

CSRの場合は ↓ で起動できるはずです。
```
rustup target add wasm32-unknown-unknown
cargo install --locked trunk
cargo install --locked wasm-bindgen-cli
git clone https://github.com/safx/leptos-taskboard-sample
cd leptos-taskboard-sample
trunk serve --filehash=false --features=csr --release --open
```

SSR + Hydration の場合は上記からさらに、↓で起動できます
```
cargo install wasm-pack
wasm-pack build --target=web --features=hydrate --release
cargo run --bin server --features=ssr --release
```

最新のRustと最新のLeptosで手元の環境で動くことは確認していますので、
- どういう手順でコマンドを実行して、どういうエラーが出ているのか
- お使いのOSなどの環境
などを教えていただけるとありがたいです。

**Comment by blueink-ao** [comment]
@safx  様

ご返信いただきまして有難うございます。

無事、私の環境で実行することができました！
お手数おかけしました。
どうもありがとうございました＾＾

原因は、cargo install --locked trunk　
のコマンドを忘れていたことでした。

まだRUST初学者でして＾＾；
基本の文法はある程度覚えたので
次のステップとして、気になる分野のサンプルコードなどを見て
勉強しているところでした。
WASMやtrunkの意味がまだよく理解できないまま、
cargo run をすぐにしてしまっていました（笑）

面白い動作のアプリですね。こちらのコードで
勉強させていただきます。
どうも有難うございました。

**Comment by safx** [comment]
報告ありがとうございます。無事実行できたようで安心いたしました。
